version: '3.7'
services:
  postgres:
    image: postgres:13
    container_name: postgres_db
    ports:
      - '5432:5432'
    environment:
      POSTGRES_DB: MoodJournal
      POSTGRES_USER: postgres.vplvfutqeylefxlacdxu
      POSTGRES_PASSWORD: Bd6BI527ZdGjv52X
    volumes:
      - postgres_data:/var/lib/postgresql/data
volumes:
  postgres_data: